build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
args:
  EASY_ADD_VERSION: "0.8.14"
  ENTRYPOINT_DEMOTER_VERSION: "0.5.0"
  SET_PROPERTY_VERSION: "0.1.6"
  RESTIFY_VERSION: "1.7.16"
  MC_MONITOR_VERSION: "0.16.7"
  RCON_CLI_VERSION: "1.7.6"
  MC_SERVER_RUNNER_VERSION: "1.15.0"
labels:
  org.opencontainers.image.title: "Minecraft Java Server (HA Add-on)"
  org.opencontainers.image.description: "Java Edition server with manual server.jar installation"
